[package]
name = "rascii"
version = "0.1.0"
authors = ["Stepan Khodzhaian <stepan.khodzhaian@carwow.co.uk>"]
edition = "2018"

[dependencies]
image = "0.21.0"
gif = "0.10.1"
regex = "1"
clap = {version = "~2.32.0", features = ["yaml"]}
