[package]
name = "rascii"
version = "0.3.0"
authors = ["Stepan Khodzhaian <mightykho.dev@gmail.com>"]
edition = "2018"

[dependencies]
termcolor = "1.0.4"
image = "0.21.0"
gif = "0.10.1"
regex = "1"
clap = {version = "~2.32.0", features = ["yaml"]}
